[build]
  functions = "netlify/functions"
  publish = "frontend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/chart/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/threats/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api"
  status = 200
